name: CI

on:
  push:
    branches:
    - feature/github-actions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Umgebung vorbereiten
        uses: docker://php:latest
      - uses: docker://composer:latest
      - name: Auschecken des Repository
        uses: actions/checkout@v2
        with:
          repository: 'Bennet187/connector-prestashop'
          ref: 'feature/github-actions'
          clean: 'false'
      - name: Buildprozess
        run: |
          ./build.sh
#          cd $GITHUB_WORKSPACE
      - if: success()
        name: Dateien in FTP ablegen
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          ARGS: --verbose --ignore-time
          REMOTE_DIR: build
          LOCAL_DIR: build
