name: CI

on:
  push:
    branches:
    - feature/github-actions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: PHP- und Composer-Setup
        uses: shivammathur/setup-php@v1
        with: 
          php-version: '7.4'
          ini-values: phar.readonly=Off
      - uses: docker://composer:latest
      - name: Repo auschecken
        uses: actions/checkout@v2
        with:
          repository: 'Bennet187/connector-prestashop'
          ref: 'feature/github-actions'
          clean: 'false'
      - name: Buildprozess
        run: |
          sudo mysql -v
      #    ./build.sh
      #    mkdir zip
      #    mv *.zip $GITHUB_WORKSPACE/zip
      #- if: success()
      #  name: FTP Upload
      #  uses: SamKirkland/FTP-Deploy-Action@2.0.0
      #  env:
      #    FTP_SERVER: ${{ secrets.FTP_SERVER }}
      #    FTP_USERNAME: ${{ secrets.FTP_USER }}
      #    FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      #    ARGS: --verbose 
      #    REMOTE_DIR: build
      #    LOCAL_DIR: zip
