name: Integrationstests

on:
  push:
    branches:
    - feature/github-actions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://composer:latest
      - uses: shivammathur/setup-php@v1
        with: 
          php-version: '7.2'
          ini-values: phar.readonly=Off  
      - uses: actions/checkout@v2
        with:
          repository: 'Bennet187/connector-prestashop'
          ref: 'feature/github-actions'
          clean: 'false'

      - name: Apache & PHP-Erweiterungen installieren
        run: |
            sudo apt-get update
            sudo apt-get install apache2
            sudo add-apt-repository -y ppa:ondrej/php
            sudo apt-get install php7.2-intl
                  
      - name: PrestaShop installieren
        run: |
            mysql -u root -proot -e 'CREATE DATABASE prestashop'
            cd /var/www/html
            sudo wget -nv https://codeload.github.com/PrestaShop/PrestaShop/zip/1.7.6.3
            sudo unzip -qq 1.7.6.3
            sudo mv /var/www/html/PrestaShop-1.7.6.3/* /var/www/html/
            sudo chmod -R 777 /var/www/
            composer install
            cd /var/www/html/install-dev
            sudo php index_cli.php --domain=localhost --db_server=localhost --db_name=prestashop --db_user=root --db_password=root

      - name: JTL-PrestaShop-Connector bauen
        run: |
            cd $GITHUB_WORKSPACE
            ./build.sh
            mkdir zip
            mv *.zip $GITHUB_WORKSPACE/zip
            
      - name: JTL-Connector installieren
        run: |
            sudo mkdir --parents /var/www/html/modules/jtlconnector
            sudo mv $GITHUB_WORKSPACE/* /var/www/html/modules/jtlconnector
            sudo mv /var/www/html/modules/jtlconnector/zip $GITHUB_WORKSPACE     
            cd /var/www/html/modules/jtlconnector
            sudo mkdir logs
            sudo chmod -R 777 logs
            composer update
            cd /var/www/html
            sudo php bin/console prestashop:module install jtlconnector

      - name: Integrationstests
        run: |
            printf "<VirtualHost  *:80>\nServerAdmin webmaster@localhost\nDocumentRoot /var/www/html\nServerName prestatest.lan\nServerAlias *.prestatest.lan\nErrorLog logs/prestatest.lan-error_log\nCustomLog logs/prestatest.lan-access_log common\n</VirtualHost>" | sudo tee /etc/apache2/sites-available/prestatest.lan.conf
            sudo mkdir /etc/apache2/logs
            sudo chmod -R 777 /etc/apache2/logs
            sudo chmod -R 777 /etc/hosts
            sudo echo "127.0.0.1  prestatest.lan" >> /etc/hosts
            sudo a2ensite prestatest.lan.conf
            sudo /etc/init.d/apache2 restart
            token=$(mysql -u root -proot prestashop -se 'SELECT value FROM `ps_configuration` WHERE name="jtlconnector_pass"')
            printf "{\"connector_url\": \"prestatest.lan\", \"connector_token\": \"$token\"}" | sudo tee /var/www/html/tests/phpunit-conf.json
            cd /var/www/html/modules/jtlconnector
            ls /var/www/html/modules/jtlconnector
            cat /var/www/html/phpunit.xml
            sudo ./library/bin/phpunit -c /var/www/html/modules/jtlconnector/phpunit.xml /var/www/html/modules/jtlconnector

      - if: success()
        name: FTP Upload
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          ARGS: --verbose 
          REMOTE_DIR: build
          LOCAL_DIR: zip
